version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/yoshihara/blog

    steps:
      - checkout

      - restore_cache:
          keys:
            - hugo-0.51

      - run:
          name: install hugo
          command: |
            wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.tar.gz
            tar xvf hugo_0.51_Linux-64bit.tar.gz

      - run:
          name: pull template
          command: |
            git submodule update -i

      - run:
          name: tweak frontmatter for hugo
          command: |
            ./bin/format_esa_md_for_hugo.sh

      - run:
          name: generate
          command: |
            ./hugo

      - run:
          name: commit & push docs/
          command: |
            git config user.email "yoshihara+circleci@users.noreply.github.com"
            git config user.name "yoshihara+circleci"
            git add docs static
            git commit -m '[ci skip] Update posts by CircleCI'
            git push origin master

      - save_cache:
          key: hugo-0.51
          paths:
            - "./hugo"
