version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.8

    working_directory: /go/src/github.com/yoshihara/blog

    steps:
      - checkout
      - run:
          name: install awscli
          command: sudo apt-get update && sudo apt-get install -y awscli

      - restore_cache:
          keys:
            - hugo-0.37.1

      - run:
          name: install hugo
          command: |
            wget https://github.com/gohugoio/hugo/releases/download/v0.37.1/hugo_0.37.1_Linux-64bit.tar.gz
            tar xvf hugo_0.37.1_Linux-64bit.tar.gz

      # awscliに必要な認証はCircleCIのBUILD SETTINGS > Environment Variables で設定している
      - run:
          name: build and upload
          command: |
            git submodule update -i
            ./bin/format_esa_md_for_hugo.sh
            ./hugo
            aws s3 sync public s3://blog.bomberowl.org/ --delete

      - save_cache:
          key: hugo-0.37.1
          paths:
            - "./hugo"
